// 套装定义及效果配置
const SETS_DATABASE = {
  wasteland: {
    name: "废土生存者套装",
    requiredCount: 4, // 4件套触发效果
    bonusPower: 50, // 战力额外加成
    desc: "凑齐4件可获得生存经验加成与战力提升",
  },
  powerArmor: {
    name: "T-60 动力装甲套装",
    requiredCount: 4,
    bonusPower: 120,
    desc: "重型废土科技，大幅提升硬实力",
  },
  netrunner: {
    name: "黑客战术套装",
    requiredCount: 4,
    bonusPower: 90,
    desc: "敏捷与算力的结晶，隐秘而致命",
  },
};

// 装备品质定义
const RARITIES = ["common", "uncommon", "rare", "epic", "legendary", "mythic"];
const SLOTS = ["head", "armor", "hand", "leg", "ring"];

// 装备数据库：5个部位 * 6种品质 * 每种品质3个不同名称
const ITEMS_DATABASE = [
  // --- 1. 废土生存者系列 (wasteland) ---
  {
    id: "w1_h_c",
    name: "破布头巾",
    type: "head",
    rarity: "common",
    power: 5,
    price: 10,
    setName: "wasteland",
    icon: "🧢",
  },
  {
    id: "w1_h_u",
    name: "皮质风帽",
    type: "head",
    rarity: "uncommon",
    power: 12,
    price: 25,
    setName: "wasteland",
    icon: "🦊",
  },
  {
    id: "w1_h_r",
    name: "防尘战术头盔",
    type: "head",
    rarity: "rare",
    power: 28,
    price: 70,
    setName: "wasteland",
    icon: "🪖",
  },
  {
    id: "w1_h_e",
    name: "强化合金头盔",
    type: "head",
    rarity: "epic",
    power: 65,
    price: 180,
    setName: "wasteland",
    icon: "🛡️",
  },
  {
    id: "w1_h_l",
    name: "荒野游侠面具",
    type: "head",
    rarity: "legendary",
    power: 150,
    price: 500,
    setName: "wasteland",
    icon: "👺",
  },
  {
    id: "w1_h_m",
    name: "旧时代联邦军官帽",
    type: "head",
    rarity: "mythic",
    power: 350,
    price: 1500,
    setName: "wasteland",
    icon: "👑",
  },

  {
    id: "w1_a_c",
    name: "缝补皮夹克",
    type: "armor",
    rarity: "common",
    power: 8,
    price: 15,
    setName: "wasteland",
    icon: "🧥",
  },
  {
    id: "w1_a_u",
    name: "加厚夹克衫",
    type: "armor",
    rarity: "uncommon",
    power: 18,
    price: 35,
    setName: "wasteland",
    icon: "🥼",
  },
  {
    id: "w1_a_r",
    name: "轻型防弹衣",
    type: "armor",
    rarity: "rare",
    power: 40,
    price: 100,
    setName: "wasteland",
    icon: "🦺",
  },
  {
    id: "w1_a_e",
    name: "重型防爆护甲",
    type: "armor",
    rarity: "epic",
    power: 90,
    price: 250,
    setName: "wasteland",
    icon: "🦾",
  },
  {
    id: "w1_a_l",
    name: "游侠战术胸甲",
    type: "armor",
    rarity: "legendary",
    power: 200,
    price: 700,
    setName: "wasteland",
    icon: "🤖",
  },
  {
    id: "w1_a_m",
    name: "联邦特勤作战服",
    type: "armor",
    rarity: "mythic",
    power: 480,
    price: 2000,
    setName: "wasteland",
    icon: "✨",
  },

  {
    id: "w1_ha_c",
    name: "布手套",
    type: "hand",
    rarity: "common",
    power: 3,
    price: 6,
    setName: "wasteland",
    icon: "🧤",
  },
  {
    id: "w1_ha_u",
    name: "皮革护手",
    type: "hand",
    rarity: "uncommon",
    power: 8,
    price: 18,
    setName: "wasteland",
    icon: "🥊",
  },
  {
    id: "w1_ha_r",
    name: "战术半指手套",
    type: "hand",
    rarity: "rare",
    power: 18,
    price: 50,
    setName: "wasteland",
    icon: "✊",
  },
  {
    id: "w1_ha_e",
    name: "合金加固手套",
    type: "hand",
    rarity: "epic",
    power: 40,
    price: 120,
    setName: "wasteland",
    icon: "🦾",
  },
  {
    id: "w1_ha_l",
    name: "游侠射击护腕",
    type: "hand",
    rarity: "legendary",
    power: 90,
    price: 350,
    setName: "wasteland",
    icon: "🏹",
  },
  {
    id: "w1_ha_m",
    name: "纳米神经控制手套",
    type: "hand",
    rarity: "mythic",
    power: 220,
    price: 900,
    setName: "wasteland",
    icon: "⚡",
  },

  {
    id: "w1_l_c",
    name: "破旧布裤",
    type: "leg",
    rarity: "common",
    power: 4,
    price: 8,
    setName: "wasteland",
    icon: "👖",
  },
  {
    id: "w1_l_u",
    name: "耐磨工装裤",
    type: "leg",
    rarity: "uncommon",
    power: 10,
    price: 22,
    setName: "wasteland",
    icon: "👖",
  },
  {
    id: "w1_l_r",
    name: "战术护膝长裤",
    type: "leg",
    rarity: "rare",
    power: 22,
    price: 60,
    setName: "wasteland",
    icon: "🩳",
  },
  {
    id: "w1_l_e",
    name: "防爆重型裤甲",
    type: "leg",
    rarity: "epic",
    power: 50,
    price: 150,
    setName: "wasteland",
    icon: "🛡️",
  },
  {
    id: "w1_l_l",
    name: "游侠机动战术腿铠",
    type: "leg",
    rarity: "legendary",
    power: 110,
    price: 400,
    setName: "wasteland",
    icon: "🦿",
  },
  {
    id: "w1_l_m",
    name: "高强度外骨骼腿甲",
    type: "leg",
    rarity: "mythic",
    power: 260,
    price: 1100,
    setName: "wasteland",
    icon: "🦾",
  },

  {
    id: "w1_r_c",
    name: "生锈铁指环",
    type: "ring",
    rarity: "common",
    power: 2,
    price: 12,
    setName: "wasteland",
    icon: "💍",
  },
  {
    id: "w1_r_u",
    name: "铜制简易戒",
    type: "ring",
    rarity: "uncommon",
    power: 6,
    price: 30,
    setName: "wasteland",
    icon: "💍",
  },
  {
    id: "w1_r_r",
    name: "刻纹银戒",
    type: "ring",
    rarity: "rare",
    power: 15,
    price: 80,
    setName: "wasteland",
    icon: "💍",
  },
  {
    id: "w1_r_e",
    name: "黄金护符戒指",
    type: "ring",
    rarity: "epic",
    power: 35,
    price: 200,
    setName: "wasteland",
    icon: "💍",
  },
  {
    id: "w1_r_l",
    name: "旧时代遗物金戒",
    type: "ring",
    rarity: "legendary",
    power: 80,
    price: 600,
    setName: "wasteland",
    icon: "💍",
  },
  {
    id: "w1_r_m",
    name: "避难所核心密钥戒",
    type: "ring",
    rarity: "mythic",
    power: 200,
    price: 1800,
    setName: "wasteland",
    icon: "💎",
  },

  // --- 2. T-60 动力装甲系列 (powerArmor) ---
  {
    id: "pa_h_c",
    name: "废铁焊接头盔",
    type: "head",
    rarity: "common",
    power: 6,
    price: 12,
    setName: "powerArmor",
    icon: "🪖",
  },
  {
    id: "pa_h_u",
    name: "装甲面罩",
    type: "head",
    rarity: "uncommon",
    power: 15,
    price: 30,
    setName: "powerArmor",
    icon: "🛡️",
  },
  {
    id: "pa_h_r",
    name: "T-45动力头盔",
    type: "head",
    rarity: "rare",
    power: 35,
    price: 90,
    setName: "powerArmor",
    icon: "🤖",
  },
  {
    id: "pa_h_e",
    name: "T-51b重型头盔",
    type: "head",
    rarity: "epic",
    power: 75,
    price: 220,
    setName: "powerArmor",
    icon: "🦾",
  },
  {
    id: "pa_h_l",
    name: "T-60核心战术头盔",
    type: "head",
    rarity: "legendary",
    power: 180,
    price: 650,
    setName: "powerArmor",
    icon: "🚀",
  },
  {
    id: "pa_h_m",
    name: "X-01地狱火面具",
    type: "head",
    rarity: "mythic",
    power: 400,
    price: 1800,
    setName: "powerArmor",
    icon: "🔥",
  },

  {
    id: "pa_a_c",
    name: "加厚铁皮胸甲",
    type: "armor",
    rarity: "common",
    power: 10,
    price: 20,
    setName: "powerArmor",
    icon: "🦺",
  },
  {
    id: "pa_a_u",
    name: "焊接钢板外壳",
    type: "armor",
    rarity: "uncommon",
    power: 22,
    price: 50,
    setName: "powerArmor",
    icon: "🛡️",
  },
  {
    id: "pa_a_r",
    name: "T-45动力胸甲",
    type: "armor",
    rarity: "rare",
    power: 50,
    price: 130,
    setName: "powerArmor",
    icon: "🤖",
  },
  {
    id: "pa_a_e",
    name: "T-51b聚变胸甲",
    type: "armor",
    rarity: "epic",
    power: 110,
    price: 320,
    setName: "powerArmor",
    icon: "🦾",
  },
  {
    id: "pa_a_l",
    name: "T-60重型动力装甲",
    type: "armor",
    rarity: "legendary",
    power: 250,
    price: 900,
    setName: "powerArmor",
    icon: "🚀",
  },
  {
    id: "pa_a_m",
    name: "X-01微型反应堆装甲",
    type: "armor",
    rarity: "mythic",
    power: 550,
    price: 2500,
    setName: "powerArmor",
    icon: "☢️",
  },

  {
    id: "pa_ha_c",
    name: "粗制铁手套",
    type: "hand",
    rarity: "common",
    power: 4,
    price: 8,
    setName: "powerArmor",
    icon: "🥊",
  },
  {
    id: "pa_ha_u",
    name: "铆钉护手",
    type: "hand",
    rarity: "uncommon",
    power: 10,
    price: 22,
    setName: "powerArmor",
    icon: "✊",
  },
  {
    id: "pa_ha_r",
    name: "T-45动力抓握手爪",
    type: "hand",
    rarity: "rare",
    power: 22,
    price: 60,
    setName: "powerArmor",
    icon: "🦾",
  },
  {
    id: "pa_ha_e",
    name: "T-51b液压重拳手",
    type: "hand",
    rarity: "epic",
    power: 48,
    price: 150,
    setName: "powerArmor",
    icon: "💥",
  },
  {
    id: "pa_ha_l",
    name: "T-60伺服驱动铁拳",
    type: "hand",
    rarity: "legendary",
    power: 110,
    price: 420,
    setName: "powerArmor",
    icon: "⚡",
  },
  {
    id: "pa_ha_m",
    name: "X-01歼灭者动力拳套",
    type: "hand",
    rarity: "mythic",
    power: 250,
    price: 1200,
    setName: "powerArmor",
    icon: "☄️",
  },

  {
    id: "pa_l_c",
    name: "重铁护腿",
    type: "leg",
    rarity: "common",
    power: 5,
    price: 10,
    setName: "powerArmor",
    icon: "👖",
  },
  {
    id: "pa_l_u",
    name: "钢板腿甲",
    type: "uncommon",
    power: 12,
    price: 28,
    setName: "powerArmor",
    icon: "🦿",
  },
  {
    id: "pa_l_r",
    name: "T-45液压重腿",
    type: "rare",
    power: 28,
    price: 75,
    setName: "powerArmor",
    icon: "🤖",
  },
  {
    id: "pa_l_e",
    name: "T-51b平衡腿铠",
    type: "epic",
    power: 60,
    price: 180,
    setName: "powerArmor",
    icon: "🦾",
  },
  {
    id: "pa_l_l",
    name: "T-60全地形动力足",
    type: "legendary",
    power: 135,
    price: 500,
    setName: "powerArmor",
    icon: "🚀",
  },
  {
    id: "pa_l_m",
    name: "X-01反重力喷射腿甲",
    type: "mythic",
    power: 300,
    price: 1400,
    setName: "powerArmor",
    icon: "🛸",
  },

  {
    id: "pa_r_c",
    name: "粗糙铁指环",
    type: "ring",
    rarity: "common",
    power: 2,
    price: 15,
    setName: "powerArmor",
    icon: "💍",
  },
  {
    id: "pa_r_u",
    name: "液压密封环",
    type: "uncommon",
    power: 7,
    price: 35,
    setName: "powerArmor",
    icon: "💍",
  },
  {
    id: "pa_r_r",
    name: "军用战术控制环",
    type: "rare",
    power: 18,
    price: 90,
    setName: "powerArmor",
    icon: "💍",
  },
  {
    id: "pa_r_e",
    name: "聚变核心微型戒",
    type: "epic",
    power: 40,
    price: 220,
    setName: "powerArmor",
    icon: "💍",
  },
  {
    id: "pa_r_l",
    name: "钢铁兄弟会荣誉戒",
    type: "legendary",
    power: 95,
    price: 700,
    setName: "powerArmor",
    icon: "💍",
  },
  {
    id: "pa_r_m",
    name: "战术AI主控智脑戒",
    type: "mythic",
    power: 220,
    price: 2000,
    setName: "powerArmor",
    icon: "💎",
  },

  // --- 3. 黑客战术系列 (netrunner) ---
  {
    id: "nr_h_c",
    name: "旧数据网线头套",
    type: "head",
    rarity: "common",
    power: 4,
    price: 10,
    setName: "netrunner",
    icon: "🎧",
  },
  {
    id: "nr_h_u",
    name: "简易神经接口帽",
    type: "head",
    rarity: "uncommon",
    power: 10,
    price: 25,
    setName: "netrunner",
    icon: "🧠",
  },
  {
    id: "nr_h_r",
    name: "赛博战术全息镜",
    type: "head",
    rarity: "rare",
    power: 25,
    price: 75,
    setName: "netrunner",
    icon: "👓",
  },
  {
    id: "nr_h_e",
    name: "量子解码头显",
    type: "head",
    rarity: "epic",
    power: 58,
    price: 170,
    setName: "netrunner",
    icon: "🥽",
  },
  {
    id: "nr_h_l",
    name: "神经矩阵潜行面具",
    type: "head",
    rarity: "legendary",
    power: 135,
    price: 520,
    setName: "netrunner",
    icon: "👤",
  },
  {
    id: "nr_h_m",
    name: "神经网主宰全息头冠",
    type: "head",
    rarity: "mythic",
    power: 320,
    price: 1600,
    setName: "netrunner",
    icon: "🌐",
  },

  {
    id: "nr_a_c",
    name: "轻便纤维夹克",
    type: "armor",
    rarity: "common",
    power: 7,
    price: 15,
    setName: "netrunner",
    icon: "🧥",
  },
  {
    id: "nr_a_u",
    name: "防电磁波风衣",
    type: "armor",
    rarity: "uncommon",
    power: 16,
    price: 40,
    setName: "netrunner",
    icon: "🧥",
  },
  {
    id: "nr_a_r",
    name: "赛博潜行风衣",
    type: "armor",
    rarity: "rare",
    power: 36,
    price: 110,
    setName: "netrunner",
    icon: "🧥",
  },
  {
    id: "nr_a_e",
    name: "纳米光学迷彩服",
    type: "armor",
    rarity: "epic",
    power: 82,
    price: 260,
    setName: "netrunner",
    icon: "✨",
  },
  {
    id: "nr_a_l",
    name: "幽灵级潜行矩阵甲",
    type: "armor",
    rarity: "legendary",
    power: 190,
    price: 750,
    setName: "netrunner",
    icon: "👻",
  },
  {
    id: "nr_a_m",
    name: "神经网隐匿主宰风衣",
    type: "armor",
    rarity: "mythic",
    power: 450,
    price: 2200,
    setName: "netrunner",
    icon: "🌌",
  },

  {
    id: "nr_ha_c",
    name: "触控导电手套",
    type: "hand",
    rarity: "common",
    power: 3,
    price: 7,
    setName: "netrunner",
    icon: "🧤",
  },
  {
    id: "nr_ha_u",
    name: "数据接口手套",
    type: "hand",
    rarity: "uncommon",
    power: 7,
    price: 18,
    setName: "netrunner",
    icon: "🖐️",
  },
  {
    id: "nr_ha_r",
    name: "神经编织黑客护腕",
    type: "hand",
    rarity: "rare",
    power: 16,
    price: 50,
    setName: "netrunner",
    icon: "⌚",
  },
  {
    id: "nr_ha_e",
    name: "量子极速触控手套",
    type: "hand",
    rarity: "epic",
    power: 36,
    price: 120,
    setName: "netrunner",
    icon: "⌨️",
  },
  {
    id: "nr_ha_l",
    name: "幻影数据窃取护手",
    type: "hand",
    rarity: "legendary",
    power: 85,
    price: 380,
    setName: "netrunner",
    icon: "💡",
  },
  {
    id: "nr_ha_m",
    name: "神经网终极终端指套",
    type: "hand",
    rarity: "mythic",
    power: 200,
    price: 1000,
    setName: "netrunner",
    icon: "💻",
  },

  {
    id: "nr_l_c",
    name: "轻质紧身裤",
    type: "leg",
    rarity: "common",
    power: 3,
    price: 8,
    setName: "netrunner",
    icon: "👖",
  },
  {
    id: "nr_l_u",
    name: "防滑跑动长裤",
    type: "uncommon",
    power: 9,
    price: 20,
    setName: "netrunner",
    icon: "👖",
  },
  {
    id: "nr_l_r",
    name: "赛博疾行护腿",
    type: "rare",
    power: 20,
    price: 60,
    setName: "netrunner",
    icon: "🦿",
  },
  {
    id: "nr_l_e",
    name: "反重力潜行靴",
    type: "epic",
    power: 45,
    price: 140,
    setName: "netrunner",
    icon: "👟",
  },
  {
    id: "nr_l_l",
    name: "幽灵步态机械长靴",
    type: "legendary",
    power: 100,
    price: 420,
    setName: "netrunner",
    icon: "🥾",
  },
  {
    id: "nr_l_m",
    name: "神经网光速跃迁足具",
    type: "mythic",
    power: 240,
    price: 1300,
    setName: "netrunner",
    icon: "🌠",
  },

  {
    id: "nr_r_c",
    name: "数据铜环",
    type: "ring",
    rarity: "common",
    power: 2,
    price: 10,
    setName: "netrunner",
    icon: "💍",
  },
  {
    id: "nr_r_u",
    name: "解码芯片戒",
    type: "uncommon",
    power: 5,
    price: 25,
    setName: "netrunner",
    icon: "💍",
  },
  {
    id: "nr_r_r",
    name: "防火墙算法戒指",
    type: "rare",
    rarity: "rare",
    power: 14,
    price: 70,
    setName: "netrunner",
    icon: "💍",
  },
  {
    id: "nr_r_e",
    name: "AI黑客辅助核心戒",
    type: "epic",
    power: 32,
    price: 180,
    setName: "netrunner",
    icon: "💍",
  },
  {
    id: "nr_r_l",
    name: "神经矩阵主控晶戒",
    type: "legendary",
    power: 75,
    price: 550,
    setName: "netrunner",
    icon: "💍",
  },
  {
    id: "nr_r_m",
    name: "深网终极管理员指环",
    type: "mythic",
    power: 180,
    price: 1700,
    setName: "netrunner",
    icon: "🔮",
  },
];
